### ISSUE TITLE
Discover issue in main.js file of my coding partner repository

### ISSUE THREAD

**Issue by naji-97** [AbdelazizSoliman/Menu-mobile#3]
Hi @AbdelazizSoliman 

Good job so far!
There are some issues that you still need to work on it
Kindly try to prevent the user from submitting the form. if there's any error with his data

**Comment by AbdelazizSoliman** [comment]
Hi @naji-97 
Thank you for your feedback, I updated the main.js to prevent the user from submitting the form if there's any error with his data.
